experiment:
  id: fern_hr_tiny
  # id: fern_lr_hr_tiny
  logdir: logs
  randomseed: 42
  gpu_id: 1
  train_iters: 250000
  validate_every: 50000
  save_every: 50000
  print_every: 10000

dataset:
  type: llff
  basedir: data/nerf_llff_data/fern
  no_ndc: False
  near: 0
  far: 1
  downsample_factor: 4
  # relative_lr_factor: 4
  # hr_fps: 60
  # hr_frequency: 5
  llffhold: 8

models:
  coarse:
    type: FlexibleNeRFModel
    num_layers: 4
    hidden_size: 64
    skip_connect_every: 3
    include_input_xyz: True
    num_encoding_fn_xyz: 6
    use_viewdirs: True
    include_input_dir: True
    num_encoding_fn_dir: 4
    log_sampling_xyz: True
    log_sampling_dir: True
  fine:
    type: FlexibleNeRFModel
    num_layers: 4
    hidden_size: 64
    skip_connect_every: 3
    num_encoding_fn_xyz: 6
    include_input_xyz: True
    use_viewdirs: True
    include_input_dir: True
    num_encoding_fn_dir: 4
    log_sampling_xyz: True
    log_sampling_dir: True

# Optimizer params.
optimizer:
  type: Adam
  lr: 5.0E-4

# Learning rate schedule.
scheduler:
  lr_decay: 250
  lr_decay_factor: 0.1

# NeRF parameters.
nerf:
  use_viewdirs: True
  encode_position_fn: positional_encoding
  encode_direction_fn: positional_encoding
  train:
    num_random_rays: 4096  # 32 * 32 * 4
    chunksize: 65536  # 1024 * 32
    perturb: True
    num_coarse: 64
    num_fine: 128
    white_background: False
    radiance_field_noise_std: 1.
    lindisp: False
  validation:
    chunksize: 65536  # 1024 * 32
    perturb: False
    num_coarse: 64
    num_fine: 128
    white_background: False
    radiance_field_noise_std: 0.
    lindisp: False
