experiment:
  id: fern_hr
  logdir: logs
  randomseed: 42
  train_iters: 250000
  validate_every: 50000
  save_every: 50000
  print_every: 10000

dataset:
  type: llff
  basedir: data/nerf_llff_data/fern
  # Optionally, provide a path to the pre-cached dataset dir. This
  # overrides the other dataset options.
  # cachedir: cache/fern/full
  # cachedir_lr: cache/fern/tiny
  # hr_fps_factor: 10
  # hr_bias: 5
  no_ndc: False
  near: 0
  far: 1
  downsample_factor: 4
  llffhold: 8

models:
  coarse:
    type: FlexibleNeRFModel
    num_layers: 8
    hidden_size: 256
    skip_connect_every: 4
    include_input_xyz: True
    num_encoding_fn_xyz: 6
    use_viewdirs: True
    include_input_dir: True
    num_encoding_fn_dir: 4
    log_sampling_xyz: True
    log_sampling_dir: True
  fine:
    type: FlexibleNeRFModel
    num_layers: 8
    hidden_size: 256
    skip_connect_every: 4
    num_encoding_fn_xyz: 6
    include_input_xyz: True
    use_viewdirs: True
    include_input_dir: True
    num_encoding_fn_dir: 4
    log_sampling_xyz: True
    log_sampling_dir: True

# Optimizer params.
optimizer:
  type: Adam
  lr: 5.0E-4

# Learning rate schedule.
scheduler:
  lr_decay: 250
  lr_decay_factor: 0.1

# NeRF parameters.
nerf:
  use_viewdirs: True
  encode_position_fn: positional_encoding
  encode_direction_fn: positional_encoding
  train:
    num_random_rays: 4096  # 32 * 32 * 4
    chunksize: 32768  # 1024 * 32
    perturb: True
    num_coarse: 64
    num_fine: 128
    white_background: False
    radiance_field_noise_std: 1.
    lindisp: False
  validation:
    chunksize: 32768  # 1024 * 32
    perturb: False
    num_coarse: 64
    num_fine: 128
    white_background: False
    radiance_field_noise_std: 0.
    lindisp: False
